version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile:
        develop.Dockerfile
        # change to name of your app
    container_name: ent-rsvp
    ports:
      - 4000:4000
      - 9229:9229 # for debugger apparently
    volumes:
#      - .:/app:rw,delegated
#    volumes:
      - backend-docker-sync:/app:nocopy

    environment:
      - DB_CONNECTION_STRING=postgres://ola:@host.docker.internal/ent-rsvp

volumes: 
  backend-docker-sync:
    external: true